[funmovies]
title = "jushuofangying"
url = "https://space.bilibili.com/386186788/upload/video"
entrySelector = ".upload-video-card grid-mode"
titleSelector = ".bili-video-card__title"
linkSelector = ".bili-video-card__title a"
